### ISSUE TITLE
closing the transaction confirmation dialog does not cancel the transaction

### ISSUE THREAD

**Issue by wighawag** [MetaMask/hello#17]
I noticed that metamask transaction confirmation dialog do not cancel the transaction upon closing the dialog via the close button. Instead the transaction is added as a notification in metamask ui for later confirmation. I think it might be confusing for the user, especially after clicking explicitly on the close button. Would it not be better to cancel the transaction in that case so the dapp can inform the user?
@flyswatter replied on slack : 

```
I don’t think Chrome gives us an event to differentiate between window closing and not clicking the confirmation in time. 
So we kind of need to preserve the tx in case it was missed.
```

Maybe there are other ways ?

**Comment by kumavis** [comment]
I was expecting it to cancel and remove the tx - surprised its not
will investigate

**Comment by kumavis** [comment]
![image](https://cloud.githubusercontent.com/assets/1474978/15521775/7bd7b8a0-21c2-11e6-9bf0-db3c60c30582.png)

close (top right) just closes the notification
confirm (bottom) signs the tx
cancel (bottom) cancels the tx

I dont think the close button implies canceling a tx just dismissing the notification.

> Maybe there are other ways ?

https://developer.chrome.com/apps/notifications#type-NotificationOptions
`requireInteraction`
> Indicates that the notification should remain visible on screen until the user activates or dismisses the notification. This defaults to false.

Using `requireInteraction` still allows the close/dismiss notification action but removes the short auto-dismiss timeout.
![image](https://cloud.githubusercontent.com/assets/1474978/15521978/d957ac1e-21c3-11e6-8fa1-7481f3880528.png)

FYI theres also this event to listen to.
`chrome.notifications.onClosed.addListener(function callback)`
> The notification closed, either by the system or by user action.

**Comment by wighawag** [comment]
```requireInteraction``` is the way to go in my opinion then.

To give a bit of a context:
Dapp usualy will ask for transaction at a critical point in the app flow and as such payment request will be usualy a yes/no thing. The dapp will normally restrict input until the user accept or cancel (or timeout in which case it is considered cancel). This is how it works in mobile app too for IAP where a modal native dialog popup.

I was actually panning to open an issue on the use of "notification" as I think conceptually they do not fit the purpose of accepting or rejecting a transaction. They are also easily missed. I do not know the limitations of chrome extension so I am here assuming everything is possible: if we could have a modal popup instead of a notification this would be better.

What do you think?

**Comment by flyswatter** [comment]
I actually really like your ideas in this domain, @wighawag, but the chrome extension API has actually imposed a number of serious limitations.  I'll lay them out, and then tell you what I've been thinking since you started talking about this:

- The chrome extension pop-up cannot be opened programmatically.
- The notification is limited to 4 lines of text *or* arbitrary SVG.  We're interested in rendering our own SVG notification, this is just slightly not our highest priority.
- We *could* put a pop-up on the screen itself, probably, although it might fight for visibility with whatever website we displayed it on. The tradeoff is probably security: If we inject the approval into the page, the page could log the password, or approve the transaction, or impersonate a transaction (although the impersonated tx would do nothing).

One thing we *can* do programmatically is open up new tabs.

We could open a tab with a much more robust transaction approval method, visualization, maybe even an expandable decompiled source code of the contract being signed. If we want a robust review process, this might be our best option, and the one I think you might favor.

There are also compromise options, like providing a configurable option for whether transaction approvals are mere notifications or always initiate a new tab.

**Comment by wighawag** [comment]
@flyswatter thanks for the info on the limitations.

I agree about privileging security but I am not sure here about the distinction between popups and tabs.

I would avoid tabs as these usually cannot be closed programmatically as this would be annoying from the user point of view.

But I thought that a tab is just a popup that is open in a tab. If that is the case there might be an option to create the "tab/popup" as popup programmatically? Security wise a popup and a tab have the same security as far as I am aware.

I had a quick look at chrome api. Never touched it before, sorry if I am completely wrong but there seems to be 2 possibilities regardless of what is used currently:

1. https://developer.chrome.com/extensions/windows#method-create
this create a popup

2. https://developer.chrome.com/extensions/tabs#method-executeScript
With that you could execute a script that call window.open and create a popup

But I do not know how url works in the context of an extension. For example can you open a popup with a content specified with the extension and in that case can the page injected be prevented access to the popup via the cross domain policies?

**Comment by kumavis** [comment]
@flyswatter was reffering to the extension's "popup" window -- it cannot be opened programmatically and requires the user to click on it

![image](https://cloud.githubusercontent.com/assets/1474978/15552567/d46ab2f8-226f-11e6-86ba-6db8c5782743.png)

**Comment by wighawag** [comment]
@kumavis I actualy understood that part as referring to the extension popup:

> The chrome extension pop-up cannot be opened programmatically.

 but I understood this one to refer to "normal" popups :

> We could put a pop-up on the screen itself, probably, although it might fight for visibility with whatever website we displayed it on. The tradeoff is probably security: If we inject the approval into the page, the page could log the password, or approve the transaction, or impersonate a transaction (although the impersonated tx would do nothing)

popup are normally safe due to cross domain policy, that how my EIP (https://github.com/ethereum/EIPs/pull/107) works  but I do not know how it works in the context of metamask as an extension ?
Also not sure about password, how is it handled ? if it use window.postMessage it should be safe (cross domain policy)
impersonation is possible but would be safe here as there is no need to enter password.

I agree  though that popup are not ideal since they are not modal (what is referred as "fight for visibility" here I presume). 

I personally do not know what is best in the context of metamask, any plan to release the source code ?, I ll myself get more ideas when my dapp will progress a bit more. 

In any case the current setup is still viable if it use ```requireInteraction``` and cancel on close.

**Comment by kumavis** [comment]
> We could put a pop-up on the screen itself
yeah I think he meant a modal -- anything outside of the extension popup is a potential phishing vector -- though the password is only used for local encryption so getting that password wouldnt get you the keys.

I dont agree with `cancel on close`, I think dismissing the tx notifiction to "deal with it later" is a fine user  action

**Comment by kumavis** [comment]
we will open source on public launch -- for now, you can join the org and take a look
@wighawag https://github.com/MetaMask/

**Comment by flyswatter** [comment]
Yeah sorry, I had meant an in-page modal.

Pop over Windows (I'll call them now) are a whole additional option, which has the window management issues you've mentioned.

- Dan

**Comment by wighawag** [comment]
@kumavis thanks for the invite

regarding:
>I dont agree with cancel on close, I think dismissing the tx notifiction to "deal with it later" is a fine user action. theres a cancel button if you want to cancel.

I never saw a payment flow where a payment request can be left aside, except through multi tasking but in that case the approval is modal and inside the app. As I said in an earlier comment :
>Dapp usualy will ask for transaction at a critical point in the app flow and as such payment request will be usualy a yes/no thing. The dapp will normally restrict input until the user accept or cancel (or timeout in which case it is considered cancel). This is how it works in mobile app too for IAP where a modal native dialog popup.

Imagine you tap on a item to buy it in a mobile app, this brings up the native InApp Purchase  modal dialog. Imagine if you could dismiss the request for later and the OS do not notify the app as such. What the app is supposed to do ?

If the decision is to allow trx to be dismissed for later, a callback should be given to the app, so the app can show something else than "please wait..."
But in that case, it would break compatibility with web3 and add unnecessary complexity

**Comment by flyswatter** [comment]
### First a rant on web3

This is a good example of where I think the web3 API is inadequate for interacting with a smart blockchain-capable wallet.

The basic example is that a callback is not sufficient for multi-levels of trust in an transaction’s success. Is “success” an indication that the transaction was submitted, or that it has been verified by a peer on the blockchain, or that we’ve seen it on a valid block, or we have some number of confirmations?

This kind of multi-layer confidence is much better suited to an event emitter, in my opinion.

Since a transaction only has a single success or error callback, any nuanced event other than absolute perfect success we need to wrap as some type of error, and get Ðapp developers familiar with those errors.

Maybe we should submit an EIP around that type of issue.

Either we recommend an event-emitter returning version of sendTx, or we submit a variety of new error codes to be standardized, and feel free to call back as many times as we’d like, so that we can communicate with UIs regarding the various incomplete statuses.

### Back to Require Interaction or not

In the meanwhile, the question remains of which is the ideal flow here.

I like the *goal* of `requireInteraction`, but in practice I think there are some serious downsides:

Since we can only have two buttons, those become `accept` and `cancel`.

If we requireInteraction, and the close modal declines the transaction, that means there is no possibility of advanced transaction review.  Right now by making the notification “soft”, and providing additional tx reviewing UI in the pop-up, we have the potential to allow much more sophisticated transaction review, which I think should grow in sophistication thousands of times if Ethereum web Ðapps are to be trustworthy.

This may put some Ðapps in a precarious state, where they’re unsure if the user is there, or what, and I guess for now that’s in the Ðapp developer’s wheelhouse, they need to not block their UI when waiting for a transaction to be sent, because as a web3 provider, we don’t have any way other than stalling to let you know that a user is reviewing the proposal.

Suggesting we should rush the signing of transactions is a lot like suggesting people sign contracts carelessly. Ask Ice Tea what he thinks of that!  (I just watched Straight Outta Compton, that’s a major theme).

**Comment by wighawag** [comment]
@flyswatter  I think you convinced me that some dapp might need to handle that case but not sure what kind of dapp it would be. 

I think my dapp fit in the category where it does not make sense to wait for later though and can only ask the player to wait. I might come up with a restricted UI while waiting but anything more complicated  would add a lot more complexity on the dapp side. For example you would need to keep track of all transaction send and deal with them once they are accepted in potentially different order. the pending tx would also need to be mirrored in the dapp UI in some way. 
I guess it is fine for dapp that require such relationship with their transactions but this seems unfair for the one who do not need this

Maybe it could be an option . Dapp could request a "modal" tx which can only be accepted or canceled (and not dismissed for later)?

**Comment by wighawag** [comment]
Actually thinking a bit more about it, all the tx management (if needed) could be done on the dapp side. This will actually make more sense since the dapp would need to manage them anyway.

**Comment by flyswatter** [comment]
I was leaning that way, but wanted to make sure we met your needs.  Good to close this?

- Dan

**Comment by wighawag** [comment]
Hmm, I am not sure I have been understood with my last comment :) do you
mean you will add an option to enforce interaction and cancel on close?

Because what I meant by "dapp should handle tx" was that metamask should
not manage them (keep aside) but just make sure user approve OR disapprove

If the plan is to add the option above then we can close and see how it
goes. Else I think better to leave open. I might be thinking too much but
some other dapp developer opinion would help
On 26 May 2016 8:37 am, "Dan Finlay" <notifications@github.com> wrote:

I was leaning that way, but wanted to make sure we met your needs. Good to
close this?

- Dan

> On May 26, 2016, at 12:26 AM, wighawag <notifications@github.com> wrote:
>
> Actually thinking a bit more about it, all the tx management (if needed)
could be done on the dapp side. This will actually make more sense since
the dapp would need to manage them anyway.

>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
>

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/MetaMask/hello/issues/17#issuecomment-221799195>

**Comment by flyswatter** [comment]
Oh sorry, @wighawag, I guess I misunderstood. We might want to schedule a meeting to better understand your use case, it sounds unique to most of our dapp developing users.

First of all, we've added `requireInteraction`, so the discussion is now about whether the close modal button should dismiss the transaction for later or decline it.

As you've described it, you're making a dapp that is unique (as far as I understand) in that it's some kind of real-time game, where the transaction moves don't need much review. I think this is actually a rare use case for blockchain applications, which are high-latency by nature and whose primary advantage is that they allow trustless review of all actions.

The problem with accommodating that use case in major ways (like no longer allowing users to review transactions in detail) is that we reduce the trust of all dapps to the level of a real time game. And some of these Dapps are investment funds, markets, voting systems, things that actually should not be treated as trivially.

But tell you what, I think we could still find a middle ground. 

Here's a new idea: What if we allowed a user to mark a Dapp as trusted within MetaMask, and changed our behavior in that case?

In particular, I think we would probably mark contracts trusted by address. If a contract was marked as trusted, maybe the user could also specify to only request approval with notifications.

Long term I would still want us to do some static analysis, checking to see if that contract is forwarding any calls, and un-trust it if any of its delegated contracts changed, but if the user requests it, I think I could get behind it.

The hardest part would be developing UX for that process that was easy to implement for devs and easy to use for users.

How would that sound?  Or can you think of other middle grounds?

**Comment by wighawag** [comment]
did not expect to be the exception :)
I personally do not think giving time to the user will make them review the transactions. As usual, people will favour ease of use over security and I think a certain amount of trust will be organically build over the use of dapps. I might be wrong though and I really appreciate the care you put on security.

My project is still in its infancy and I ll revisit that issue later. Feel free to close it, I ll reopen it if I find it affect too negatively my project. It might not do.

regarding your proposal, I am not sure I like the idea of "trusted" dapps but I ll get back to you at a later time as it might be the best middle ground.

Thanks for considering my use case.

**Comment by flyswatter** [comment]
You're probably right though, that the average user might not do much review. For that reason, we're hoping to make even the notification as informative as possible, but until it is more informative, I want to be conservative about the security constraints we remove.

Please do keep the conversation moving, you've been making some great contributions to this space. Closing for now, but please reopen if you have an approach you'd like us to consider.

**Comment by flyswatter** [comment]
Opening to investigate whether there is a way to detect the window's closing with the new popup type of notification.
