### ISSUE TITLE
Exploring MetaMask

### ISSUE THREAD

**Issue by sridhar87** [MetaMask/hello#23]
Hello there,

I've developed etherfaces.com and looking to see how to integrate metamask into my DApp.

I also came across the requirements that every call made is asynchronous. Is it possible to have a hybrid? We use synchronous calls for some usecases and asynchronous for others.

Also, is there any step by step documentation on how to integrate metamask to our site? We take payments in Ether from within the browser as well and we think a service like MetaMask would make our app very simpler.

Thanks,
Etherfaces.com

**Comment by flyswatter** [comment]
It sounds like you've seen [our compatibility guide](https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md), and it is true that we're enforcing all asynchronous calls, aside from checking the current accounts. What are your use cases that you find you have to use synchronous methods?

Integration should be pretty simple, you have access to the standard web3 API. That guide I linked to is the closest thing we have to a step-by-step guide, since not every step applies to every dapp, but the guide + [the web3 API documentation](https://github.com/ethereum/wiki/wiki/JavaScript-API) should be everything you need.

Whenever you make a web3 call that requires the use of a private key, MetaMask will prompt the user for authorization automatically.

When your Dapp is MetaMask compatible, you can post it on our [compatible dapp issue](https://github.com/MetaMask/hello/issues/16) and we'll keep track of the compatibility and maybe even link to it!

**Comment by sridhar87** [comment]
I thank you for your response.

"Whenever you make a web3 call that requires the use of a private key, MetaMask will prompt the user for authorization automatically" - I missed this part about automatic authorization. I was thinking in terms of integrating through some APIs. I will check and get back to you.

So as developers, we should not require doing anything special I guess to use MetaMask, which is so cool.

Also, I've support for in-browser payment in Ether, would I be able to continue using that? - For example- sending rawTransaction that is already signed by a user to preserve backwards compatibility for my app for those who do not use MetaMask? Let me know. Thanks.

**Comment by flyswatter** [comment]
That's a good note- we should emphasize what triggers the user interaction in the compatibility guide.

You actually shouldn't need to call `sendRawTransaction`, since you won't have signed data. You will call `sendTransaction` with a hash of the transaction data to send, and we'll handle the signing and submitting to the blockchain.

**Comment by flyswatter** [comment]
I've added a section about what triggers user authorization to the compatibility guide, thanks for asking for clarification!

**Comment by sridhar87** [comment]
Ok, I did a quick try of metamask.......and it works GREAT! Where users have installed metamask, I'm changing it to Pay Securely with MetaMask.

I will push the changes to my website today. Thanks for this awesome tool. It helps in making the payments more secure and hence the trust of the app.

I will add my app to the list after I push the changes to my website.

**Comment by flyswatter** [comment]
![Perfecto!](http://i.giphy.com/l41YleLHixOeCWNe8.gif)
