### ISSUE TITLE
Need to unlock to reject tx

### ISSUE THREAD

**Issue by wighawag** [MetaMask/hello#29]
Hi, I just noticed that if the wallet is locked and the dapp want you to accept a tx, you have to unlock first before rejecting the tx.
I thing it would be good to allow rejecting the tx even if the wallet is locked. 
Especially since until the tx is rejected or accepted the dapp has no information on what happened.

**Comment by flyswatter** [comment]
Could you help me visualize the proposed flow?

You propose a tx in your dapp.
We open the tx confirmation window, but it only has a reject or unlock button?
Maybe the approval button then asks for a password?

I could see that working, since that's basically how Mist works now, that wouldn't be bad.

**Comment by wighawag** [comment]
yes, asking password after and only if approval seems like a good option

**Comment by flyswatter** [comment]
This is blocked until we implement the multi-vault support, which will include support for metadata about accounts while locked, which will make this a lot easier.
